packages:
  darwin:
    casks:
      - amethyst
      - bambu-studio
      - brave-browser
      - discord
      - font-jetbrains-mono-nerd-font
      - obsidian
      - signal
      - visual-studio-code
      - wezterm
  windows:
    winget:
      - Apple.iCloud
      - Bambulab.Bambustudio
      - Brave.Brave
      - DEVCOM.JetBrainsMonoNerdFont
      - Discord.Discord
      - Microsoft.VisualStudioCode
      - Obsidian.Obsidian
      - OpenWhisperSystems.Signal
      - wez.wezterm
  linux:
    flatpaks:
      - com.bambulab.BambuStudio
      - com.brave.Browser
      - com.discordapp.Discord
      - com.visualstudio.code
      - md.obsidian.Obsidian
      - org.signal.Signal
vscode_extensions:
  - anthropic.claude-code
  - bradlc.vscode-tailwindcss
  - buenon.scratchpads
  - catppuccin.catppuccin-vsc
