alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gcb='git checkout -b'
alias gco='git checkout'
alias gcam='git commit --all --message'
alias gcmsg='git commit --message'
alias gc!='git commit --verbose --amend'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git pull'
alias gp='git push'
alias gst='git status'
alias glog='git log --oneline --decorate --graph'

# tools
alias c='claude'
