#!/usr/bin/env python3
"""Make OrcaSlicer H2C exports openable in Bambu Studio (02.08 segfaults on them).

Studio's GCodeProcessor only applies the G-code CONFIG_BLOCK when the file says
"generated by BambuStudio" (every other producer string is commented out of its
whitelist). Orca files say "generated by OrcaSlicer", so Studio skips the config,
leaves its H2-series dual-extruder state empty (m_nozzle_group_result null,
extruder_types empty), and segfaults on the first T command / G1 time estimate.

Fix: rewrite the producer line to claim BambuStudio.
  - .gcode:      patch the header line.
  - .gcode.3mf:  patch Metadata/plate_*.gcode, regenerate plate_*.gcode.md5
                 (uppercase hex of raw bytes), and sync project_settings.config
                 filament_map to the map the plate was actually sliced with
                 (slice_info.config "filament_maps", e.g. "2 1" = filament 1 on
                 the left head; Orca writes ["1","1"] there regardless).

Usage: fix_orca_h2c_for_studio.py FILE [FILE...]   -> writes FILE with _fixed suffix
Verified 2026-08-07 against Orca 2.5.0-dev nightly + Bambu Studio 02.08.01.55.
"""
import hashlib
import json
import re
import sys
import zipfile
from pathlib import Path

PRODUCER_RE = rb"; generated by OrcaSlicer [^\r\n]*"
PRODUCER_SUB = b"; generated by BambuStudio 02.08.01.55"


def fix_gcode_bytes(data: bytes) -> bytes:
    patched, n = re.subn(PRODUCER_RE, PRODUCER_SUB, data, count=1)
    if n == 0:
        print("  (no OrcaSlicer producer line found - already fixed?)")
    return patched


def slice_info_filament_map(zin):  # -> list[str] | None (macOS system python is 3.9)
    try:
        info = zin.read("Metadata/slice_info.config").decode("utf-8", "replace")
    except KeyError:
        return None
    m = re.search(r'key="filament_maps" value="([\d ]+)"', info)
    return m.group(1).split() if m else None


def fix_3mf(src: Path, dst: Path) -> None:
    with zipfile.ZipFile(src) as zin:
        real_map = slice_info_filament_map(zin)
        with zipfile.ZipFile(dst, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                data = zin.read(item.filename)
                if re.fullmatch(r"Metadata/plate_\d+\.gcode", item.filename):
                    data = fix_gcode_bytes(data)
                elif re.fullmatch(r"Metadata/plate_(\d+)\.gcode\.md5", item.filename):
                    plate = item.filename.removesuffix(".md5")
                    data = hashlib.md5(fix_gcode_bytes(zin.read(plate))).hexdigest().upper().encode()
                elif item.filename == "Metadata/slice_info.config":
                    # Strip the new-format nozzle markers so Studio rebuilds its
                    # nozzle-group context via the backward-compat path (extruder
                    # count from nozzle_diameters). Orca's new-format shape (one
                    # <nozzle> on the left head, single-entry filament_maps) makes
                    # Studio 02.08's re-processing throw "Failed to process the
                    # G-code file ... from previous 3mf".
                    data = re.sub(rb"\s*<nozzle [^>]*/>", b"", data)
                    data = data.replace(b'group_id="1" ', b"")
                elif item.filename == "Metadata/project_settings.config" and real_map:
                    cfg = json.loads(data)
                    # Overwrite leading entries only: slice_info may list fewer values
                    # than the project has filament slots, and changing the array
                    # length risks tripping Studio's arity-strict loader.
                    old = cfg.get("filament_map", [])
                    cfg["filament_map"] = real_map[:len(old)] + old[len(real_map):] if old else real_map
                    data = json.dumps(cfg, indent=4, ensure_ascii=False).encode("utf-8")
                zout.writestr(item, data)


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    for arg in sys.argv[1:]:
        src = Path(arg)
        if src.name.endswith(".gcode.3mf") or src.suffix == ".3mf":
            dst = src.with_name(src.name.replace(".gcode.3mf", "_fixed.gcode.3mf")
                                if src.name.endswith(".gcode.3mf")
                                else src.stem + "_fixed.3mf")
            fix_3mf(src, dst)
        elif src.suffix == ".gcode":
            dst = src.with_name(src.stem + "_fixed.gcode")
            dst.write_bytes(fix_gcode_bytes(src.read_bytes()))
        else:
            print(f"skipping {src}: not a .gcode or .3mf")
            continue
        print(f"{src.name} -> {dst.name}")


if __name__ == "__main__":
    main()
